In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [33]:
data=np.array([[2,3,4,5,6,7],[1,5,3,6,7,8]])

In [34]:
mean=np.mean(data,axis=1)

In [35]:
mean

array([4.5, 5. ])

In [36]:
def sub_mean(data,mean):
    j=0
    for i in range(len(data)):
        data[i]=data[i]-mean[j]
        j+=1
    return data

In [37]:
subdata=sub_mean(data,mean)

In [38]:
subdata

array([[-2, -1,  0,  0,  1,  2],
       [-4,  0, -2,  1,  2,  3]])

In [43]:
cov=np.cov(subdata)

In [44]:
cov

array([[2. , 3.2],
       [3.2, 6.8]])

In [45]:
from numpy.linalg import eig
w,v=eig(cov)

In [46]:
w

array([0.4, 8.4])

In [47]:
v

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])