In [2]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

A = array([[2,1], [3, 5], [4,3],[5,6],[6,7],[7,8]])
print(A)

M = mean(A.T, axis=1)
print(M)

C = A - M
print(C)

V = cov(C.T)
print(V)

values, vectors = eig(V)
print(vectors)
print(values)



[[2 1]
 [3 5]
 [4 3]
 [5 6]
 [6 7]
 [7 8]]
[4.5 5. ]
[[-2.5 -4. ]
 [-1.5  0. ]
 [-0.5 -2. ]
 [ 0.5  1. ]
 [ 1.5  2. ]
 [ 2.5  3. ]]
[[3.5 4.4]
 [4.4 6.8]]
[[-0.82192562 -0.56959484]
 [ 0.56959484 -0.82192562]]
[0.45079794 9.84920206]
